### PR TITLE
TestRunner - Add option --fail-fast, don’t fail fast by default

### PR DESCRIPTION
**Pull request by jirutka**
Note: I’m not C++ developer, so I just _hope_ that I coded it right.

### CODE REVIEW

**Comment by thepowersgang** [comment]
Nice idea :) But brace style isn't quite correct.

**Comment by jirutka** [comment]
Is it better now?

**Comment by kaniini** [comment]
it looks fine to me now

**Comment by thepowersgang** [comment]
I didn't actually see any new commits after your comment... but meh, it'll probably get cleaned up in the next refactor.

**Comment by jirutka** [comment]
I've amended it to the original commit and force pushed.

**Pull request merged**
