### PR TITLE
[WIP] Build with meson

### PR DESCRIPTION
**Pull request by ubsan**
Since I'm a VS2017 user, I also made sure to get it compiling with VS2017.

This is just an initial pass. I think it's a useful comparison with #88, as I think meson is far simpler and easy to read compared to CMake.

### CODE REVIEW

**Comment by ubsan** [comment]
You'll also notice that the versions update every build, as opposed to every run of CMake, like in #88.

**Comment by thepowersgang** [comment]
Could you separate the source changes out from the new build system?

**Comment by thepowersgang** [comment]
I'm closing this PR in favour of using CMake (sorry).
However, I'd appreciate the VS2017 fixes in a separate PR.

**Comment by ubsan** [comment]
np! I'll see if I can do the thing.

**Pull request closed without merging**
