### PR TITLE
Removed side effect from typeid call (ref #236)

### PR DESCRIPTION
**Pull request by catap**
Can build it now with `-Werror=potentially-evaluated-expression`

### CODE REVIEW

**Comment by thepowersgang** [comment]
Why `const std::type_info& type_info() const;` instead of `const char* type_name() const;`

**Comment by catap** [comment]
@thepowersgang indeed

**Comment by thepowersgang** [comment]
Seems to be missing the deref - You used `typeid(m_ptr)` instead of `typeid(*m_ptr)`

**Comment by catap** [comment]
@thepowersgang this way it fails like:
```
src/ast/expr_ptr.hpp:46:44: error: 'typeid' of incomplete type 'AST::ExprNode'
    const char* type_name() const { return typeid(*m_ptr).name(); }
```

**Comment by thepowersgang** [comment]
The implementation needs to be in `expr_ptr.cpp` (or wherever the destructor implementation is)

**Comment by catap** [comment]
@thepowersgang thanks!

**Comment by thepowersgang** [comment]
Have you tested that the debug output is still good/useful?

**Comment by catap** [comment]
@thepowersgang all => nope, some => yes; but as you pointed with `*m_ptr` I defently did miss something.

**Comment by catap** [comment]
@thepowersgang I've tested it via https://github.com/thepowersgang/mrustc/pull/279 and it produces good/useful debug output.

**Pull request merged**
