### PR TITLE
codegen_c - use aggregate initialization instead of GCC statement expressions

### PR DESCRIPTION
**Pull request by arlosi**
This change uses aggregate initialization when initializing constants instead of GCC statement expressions.

Initialization of statics that are zero is skipped, since they will be zero-initialized on program startup anyway. This allows zeroed statics with more than 16 levels of nesting to be compiled with out errors on MSVC.

If a static has more than 16 levels of nesting, and is not zero-initialized, MSVC will fail with:
`C1054: compiler limit: initializers nested too deeply`

### CODE REVIEW

**Comment by arlosi** [comment]
Skipping initialization of zeroed statics is a bit of a hack, but this was the last major issue in getting rustc and cargo compiling on Windows.

**Comment by thepowersgang** [comment]
Not sure why Travis isn't running on this, but I'll merge and check manually.

**Comment by thepowersgang** [comment]
Seems to work :)

**Comment by bjorn3** [comment]
> Not sure why Travis isn't running on this

This is not the only repo Travis isn't working on.

**Pull request merged**
