### PR TITLE
targets: Add x86_64 and arm targets for Haiku

### PR DESCRIPTION
**Pull request by kallisti5**

### CODE REVIEW

**Comment by kwri-avongluck** [comment]
Anyfeedback on this one?

**Comment by kallisti5** [comment]
Any feedback on this one? Thanks!

**Comment by thepowersgang** [comment]
Sorry, been a very busy few weeks.
I assume this works? If it does, I'll just merge it.

**Comment by kallisti5** [comment]
No worries, It works :-)
I'm looking for an easier way to bootstrap rust on Haiku until we get stage0 artifacts with rust.

**Pull request merged**
